### ISSUE TITLE
error seen when spawning

### ISSUE THREAD

**Issue by RexShack** [Project-Sloth/ps-liveries#1]
any reason why I see this error when spawning
![Screenshot 2022-09-15 091556](https://user-images.githubusercontent.com/76662933/190353221-63f82e1d-e41a-4586-bf3e-21a0e7c0830e.jpg)

**Comment by Luceeiy** [comment]
Working on a fix at the moment , thank you for pointing it out! :)

**Comment by Luceeiy** [comment]
This issue was fixed with the latest update 😄
