### ISSUE TITLE
Vehicle.meta - 3 cars are not showing extras

### ISSUE THREAD

**Issue by TheMaf021** [Project-Sloth/ps-liveries#14]
In the vehicles.meta, the following code needs to be added (under the /InitDatas line).
- Otherwise, the extras (lights, etc) will not appear on these cars

2011 Vic :
```
    <txdRelationships>
	    <Item>
      <parent>vehicles_poltax_interior</parent>
      <child>pd1</child>
    </Item>
  </txdRelationships>
</CVehicleModelInfo__InitDataList>

```
2018 Charger :
```
	<txdRelationships>
   	<Item>
      <parent>vehicles_poltax_interior</parent>
      <child>Char</child>
    </Item>
	</txdRelationships>
</CVehicleModelInfo__InitDataList>
```

2020 Explorer :
```
  <txdRelationships>
	    <Item>
      <parent>vehicles_bob_brown_interior</parent>
      <child>Explorer</child>
    </Item>
  </txdRelationships>
</CVehicleModelInfo__InitDataList>
```

**Comment by TheMaf021** [comment]
I've never done a Pull Request before, so I figured a comment would be next best

**Comment by Bunny5578** [comment]
hello sorry for the late comment but i will check with this thank u

**Comment by Bunny5578** [comment]
> I've never done a Pull Request before, so I figured a comment would be next best

a update will be pused shortly
