### ISSUE TITLE
"Oversized assets" Warning

### ISSUE THREAD

**Issue by wessleym** [Project-Sloth/ps-liveries#15]
When starting this resource, I get these messages in red in the txAdmin console:
```
[ citizen-server-impl] Asset ps-liveries/Explorer.ytd uses 92.0 MiB of physical memory. Oversized assets can and WILL lead to streaming issues (models not loading/rendering, commonly known as 'texture loss', 'city bug' or 'streaming isn't great').
[ citizen-server-impl] Asset ps-liveries/Char.ytd uses 204.0 MiB of physical memory. Oversized assets can and WILL lead to streaming issues (models not loading/rendering, commonly known as 'texture loss', 'city bug' or 'streaming isn't great').
[ citizen-server-impl] Asset ps-liveries/pd1.ytd uses 114.0 MiB of physical memory. Oversized assets can and WILL lead to streaming issues (models not loading/rendering, commonly known as 'texture loss', 'city bug' or 'streaming isn't great').
```
If I'm understanding the message correctly, "citizen-server-impl" is reporting that these files _will_ cause issues.  Can anything be done to reduce their size?  Until they are revised, I don't want to use files that citizen-server-impl says will lead to streaming issues.  Please help me if I'm misunderstanding.  Thank you.

**Comment by MonkeyWhisper** [comment]
It's fine

**Comment by wessleym** [comment]
@MonkeyWhisper, can you provide any information on how "it's fine"?  citizen-server-impl disagrees with you.  Thank you.

**Comment by MonkeyWhisper** [comment]
Lol

**Comment by wessleym** [comment]
@MonkeyWhisper, I understand that you don't care about what citizen-server-impl thinks of your large YTD files.  But can you explain why you don't care?
