### ISSUE TITLE
Crown Vic Handling File

### ISSUE THREAD

**Issue by TheCrypticOG** [Project-Sloth/ps-liveries#25]
I believe there is an issue with the crown vic handling file because when I open it in VSC it looks different compared to all the others. The pic on the left is from the VIC and the one on the right is from the charger.
![mstsc_fbAZHWiHpJ](https://user-images.githubusercontent.com/98983638/214961191-45913ff8-0771-4255-ab28-f020dafc194d.png)

**Comment by Bunny5578** [comment]
Will look into this thank you for the feedback

**Comment by MonkeyWhisper** [comment]
Nothing is wrong
