### ISSUE TITLE
No handeling for 2.0 cars

### ISSUE THREAD

**Issue by FancyTrashPanda2000** [Project-Sloth/ps-liveries#32]
The only handling in the 2.0 cars is for the taurus.

[ps-liveries](https://github.com/Project-Sloth/ps-liveries/blob/main/ps-liveries2.0/Data/handling.meta)

![image](https://user-images.githubusercontent.com/93735939/230751627-22ee1999-add9-47b3-8c6c-cc2d30db0b26.png)

**Comment by MonkeyWhisper** [comment]
I know, it does not come with one
