### ISSUE TITLE
Credit

### ISSUE THREAD

**Issue by EarthLlamma** [Project-Sloth/ps-liveries#5]
Hello,

I am reaching out to your team regarding a issue I found in the credits section. In the pictures section you have a picture of the march 1 mustang which has my logo hanging from the mirror. 
![image](https://user-images.githubusercontent.com/113864572/190932212-ef001949-004a-45d2-8cdd-21da8efdba7c.png)

In the credits section at the bottom of this it says the mustang was made by Northernscot. 

Please reach out with any questions or anything to me @ EarthLlamma#1481

Thanks,
Adam

**Comment by MonkeyWhisper** [comment]
> EarthLlamma

Hi, 

You're right, I made a mistake and credited the wrong person on the read me. 

I have now fixed it and given you the proper credit along with linking your discord.
