### ISSUE TITLE
Handling

### ISSUE THREAD

**Issue by AryanSuhasKhul** [Project-Sloth/ps-liveries#6]
Can u pls provide me a nice or good handling for these vehicles as it is very fast it just goes at the speed of 180 normally.

**Comment by MonkeyWhisper** [comment]
Adjust it

**Comment by Polo4217** [comment]
@AryanSuhasKhul  I was the one that actually did the Handling files, Hopefully this helps.

Open the  handling.lua file 

Find. 


<fInitialDriveMaxFlatVel value="205.000000"/>

and 

<fInitialDriveForce value="3.000000"/>


INITIALDRIVEMAXFLATVEL
This determines the vehicle speed at redline in the top gear (not the show).   value="105.000000"/>     <---example 

Adjust both of these up and down until your happy 

FINITIALDRIVEFORCE
This modifies the game's calculation of drive force (from the output of the transmission).   value="3.000000"/>     <---example 

Hopefully this helps Polo :)
